# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [

        migrations.AddField(
            model_name='review',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified by admin'),
        ),

    ]
